[package]
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2018"
name = "aliddns"
version = "1.0.0"

[dependencies]
anyhow = "1"
base64 = "0.13"
chrono = "0.4"
curl = {version = "0.4", default-features = false}
hmac-sha1 = "0.1"
json = "0.12"
log = "0.4"
serde = {version = "1", features = ["derive"]}
toml = "0.5"
urlencoding = "2"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["heapapi", "iphlpapi"]}
windows-service = "0.4"

[profile.release]
lto = true
panic = "abort"
